name: Whats-app Client

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Client
        run: |
          cd client
          npm run build 
          if [ $? -ne 0 ]; then
            echo "Error: Application build failed!"
            exit 1
          fi
          echo "Application build successfully!"
